# Import Libaries

In [1]:
import numpy as np
import pandas as pd

# Importing Data

In [3]:
crop = pd.read_csv("D:\\AI based crop Project files\\Crop_recommendation.csv")
crop.head()

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

# Asq Six Question to yourself

In [4]:
crop.shape

(2200, 8)

In [5]:
crop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   N            2200 non-null   int64  
 1   P            2200 non-null   int64  
 2   K            2200 non-null   int64  
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object 
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB


In [6]:
crop.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [7]:
crop.duplicated().sum()

np.int64(0)

In [8]:
crop.describe()

N            P            K  temperature     humidity  \
count  2200.000000  2200.000000  2200.000000  2200.000000  2200.000000   
mean     50.551818    53.362727    48.149091    25.616244    71.481779   
std      36.917334    32.985883    50.647931     5.063749    22.263812   
min       0.000000     5.000000     5.000000     8.825675    14.258040   
25%      21.000000    28.000000    20.000000    22.769375    60.261953   
50%      37.000000    51.000000    32.000000    25.598693    80.473146   
75%      84.250000    68.000000    49.000000    28.561654    89.948771   
max     140.000000   145.000000   205.000000    43.675493    99.981876   

                ph     rainfall  
count  2200.000000  2200.000000  
mean      6.469480   103.463655  
std       0.773938    54.958389  
min       3.504752    20.211267  
25%       5.971693    64.551686  
50%       6.425045    94.867624  
75%       6.923643   124.267508  
max       9.935091   298.560117

In [9]:
crop['label'].value_counts()

label
rice           100
maize          100
chickpea       100
kidneybeans    100
pigeonpeas     100
mothbeans      100
mungbean       100
blackgram      100
lentil         100
pomegranate    100
banana         100
mango          100
grapes         100
watermelon     100
muskmelon      100
apple          100
orange         100
papaya         100
coconut        100
cotton         100
jute           100
coffee         100
Name: count, dtype: int64

# Encoding

In [10]:
crop_dict = {
    'rice': 1,
    'maize': 2,
    'jute': 3,
    'cotton': 4,
    'coconut': 5,
    'papaya': 6,
    'orange': 7,
    'apple': 8,
    'muskmelon': 9,
    'watermelon': 10,
    'grapes': 11,
    'mango': 12,
    'banana': 13,
    'pomegranate': 14,
    'lentil': 15,
    'blackgram': 16,
    'mungbean': 17,
    'mothbeans': 18,
    'pigeonpeas': 19,
    'kidneybeans': 20,
    'chickpea': 21,
    'coffee': 22
}
crop['crop_num']=  crop['label'].map(crop_dict)

In [12]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [13]:
crop

N    P    K  temperature   humidity        ph    rainfall  \
0      90   42   43    20.879744  82.002744  6.502985  202.935536   
1      85   58   41    21.770462  80.319644  7.038096  226.655537   
2      60   55   44    23.004459  82.320763  7.840207  263.964248   
3      74   35   40    26.491096  80.158363  6.980401  242.864034   
4      78   42   42    20.130175  81.604873  7.628473  262.717340   
5      69   37   42    23.058049  83.370118  7.073454  251.055000   
6      69   55   38    22.708838  82.639414  5.700806  271.324860   
7      94   53   40    20.277744  82.894086  5.718627  241.974195   
8      89   54   38    24.515881  83.535216  6.685346  230.446236   
9      68   58   38    23.223974  83.033227  6.336254  221.209196   
10     91   53   40    26.527235  81.417538  5.386168  264.614870   
11     90   46   42    23.978982  81.450616  7.502834  250.083234   
12     78   58   44    26.800796  80.886848  5.108682  284.436457   
13     93   56   36    24.014976  82.056872  6.984354  185.277339   
14     94   50   37    25.665852  80.663850  6.948020  209.586971   
15     60   48   39    24.282094  80.300256  7.042299  231.086335   
16     85   38   41    21.587118  82.788371  6.249051  276.655246   
17     91   35   39    23.793920  80.418180  6.970860  206.261186   
18     77   38   36    21.865252  80.192301  5.953933  224.555017   
19     88   35   40    23.579436  83.587603  5.853932  291.298662   
20     89   45   36    21.325042  80.474764  6.442475  185.497473   
21     76   40   43    25.157455  83.117135  5.070176  231.384316   
22     67   59   41    21.947667  80.973842  6.012633  213.356092   
23     83   41   43    21.052536  82.678395  6.254028  233.107582   
24     98   47   37    23.483813  81.332651  7.375483  224.058116   
25     66   53   41    25.075635  80.523891  7.778915  257.003887   
26     97   59   43    26.359272  84.044036  6.286500  271.358614   
27     97   50   41    24.529227  80.544986  7.070960  260.263403   
28     60   49   44    20.775761  84.497744  6.244841  240.081065   
29     84   51   35    22.301574  80.644165  6.043305  197.979121   
30     73   57   41    21.446540  84.943760  5.824709  272.201720   
31     92   35   40    22.179319  80.331272  6.357389  200.088279   
32     85   37   39    24.527837  82.736856  6.364135  224.675723   
33     98   53   38    20.267076  81.638952  5.014507  270.441727   
34     88   54   44    25.735429  83.882662  6.149411  233.132137   
35     95   55   42    26.795339  82.148087  5.950661  193.347399   
36     99   57   35    26.757542  81.177340  5.960370  272.299906   
37     95   39   36    23.863305  83.152508  5.561399  285.249365   
38     60   43   44    21.019447  82.952217  7.416245  298.401847   
39     63   44   41    24.172988  83.728757  5.583370  257.034355   
40     62   42   36    22.781338  82.067191  6.430010  248.718323   
41     64   45   43    25.629801  83.528423  5.534878  209.900198   
42     83   60   36    25.597049  80.145093  6.903986  200.834898   
43     82   40   40    23.830675  84.813601  6.271479  298.560117   
44     85   52   45    26.313555  82.366990  7.224286  265.535594   
45     91   35   38    24.897282  80.525861  6.134287  183.679321   
46     76   49   42    24.958779  84.479634  5.206373  196.956001   
47     74   39   38    23.241135  84.592018  7.782051  233.045345   
48     79   43   39    21.666283  80.709606  7.062779  210.814209   
49     88   55   45    24.635449  80.413630  7.730368  253.720278   
50     60   36   43    23.431219  83.063101  5.286204  219.904835   
51     76   60   39    20.045414  80.347756  6.766240  208.581016   
52     93   56   42    23.857240  82.225730  7.382763  195.094831   
53     65   60   43    21.971994  81.899182  5.658169  227.363701   
54     95   52   36    26.229169  83.836258  5.543360  286.508373   
55     75   38   39    23.446768  84.793524  6.215110  283.933847   
56     74   54   38    25.655535  83.470211  7.120273  217.378858   
57    

In [14]:
crop.drop(['label'],axis=1,inplace=True)
crop.head()

N   P   K  temperature   humidity        ph    rainfall  crop_num
0  90  42  43    20.879744  82.002744  6.502985  202.935536         1
1  85  58  41    21.770462  80.319644  7.038096  226.655537         1
2  60  55  44    23.004459  82.320763  7.840207  263.964248         1
3  74  35  40    26.491096  80.158363  6.980401  242.864034         1
4  78  42  42    20.130175  81.604873  7.628473  262.717340         1

# Train Test Split

In [15]:
X = crop.drop(['crop_num'],axis=1)
y = crop['crop_num']

In [19]:
print(X)

        N    P    K  temperature   humidity        ph    rainfall
0      90   42   43    20.879744  82.002744  6.502985  202.935536
1      85   58   41    21.770462  80.319644  7.038096  226.655537
2      60   55   44    23.004459  82.320763  7.840207  263.964248
3      74   35   40    26.491096  80.158363  6.980401  242.864034
4      78   42   42    20.130175  81.604873  7.628473  262.717340
5      69   37   42    23.058049  83.370118  7.073454  251.055000
6      69   55   38    22.708838  82.639414  5.700806  271.324860
7      94   53   40    20.277744  82.894086  5.718627  241.974195
8      89   54   38    24.515881  83.535216  6.685346  230.446236
9      68   58   38    23.223974  83.033227  6.336254  221.209196
10     91   53   40    26.527235  81.417538  5.386168  264.614870
11     90   46   42    23.978982  81.450616  7.502834  250.083234
12     78   58   44    26.800796  80.886848  5.108682  284.436457
13     93   56   36    24.014976  82.056872  6.984354  185.277339
14     94 

In [20]:
print(y)

0        1
1        1
2        1
3        1
4        1
5        1
6        1
7        1
8        1
9        1
10       1
11       1
12       1
13       1
14       1
15       1
16       1
17       1
18       1
19       1
20       1
21       1
22       1
23       1
24       1
25       1
26       1
27       1
28       1
29       1
30       1
31       1
32       1
33       1
34       1
35       1
36       1
37       1
38       1
39       1
40       1
41       1
42       1
43       1
44       1
45       1
46       1
47       1
48       1
49       1
50       1
51       1
52       1
53       1
54       1
55       1
56       1
57       1
58       1
59       1
60       1
61       1
62       1
63       1
64       1
65       1
66       1
67       1
68       1
69       1
70       1
71       1
72       1
73       1
74       1
75       1
76       1
77       1
78       1
79       1
80       1
81       1
82       1
83       1
84       1
85       1
86       1
87       1
88       1
89       1
90       1

In [21]:
y.shape

(2200,)

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
X_train

N    P    K  temperature   humidity        ph    rainfall
1656   17   16   14    16.396243  92.181519  6.625539  102.944161
752    37   79   19    27.543848  69.347863  7.143943   69.408782
892     7   73   25    27.521856  63.132153  7.288057   45.208411
1041  101   70   48    25.360592  75.031933  6.012697  116.553145
1179    0   17   30    35.474783  47.972305  6.279134   97.790725
162    67   51   24    23.502979  61.320261  5.584171   64.777914
1523   34  140  198    21.704170  93.440063  5.751707  115.178140
973     8   23   38    19.301063  87.177517  7.005411  105.476659
1104    0   21   32    35.898556  54.259642  6.430139   92.197217
1900  133   47   24    24.402289  79.197320  7.231325   90.802236
650    36   43   21    28.363194  84.859361  7.140438   52.930311
494    17   64   18    36.750875  58.257991  6.079385  124.602815
256    37   66   85    20.931753  18.912954  6.456148   78.069108
1503    8  120  201    21.186674  91.134357  6.321152  122.233323
2162  118   40   35    26.350342  58.506502  7.460175  121.558630
440     6   66   15    34.931742  30.400468  6.345806  159.264983
2010   89   53   44    24.886928  71.917115  7.319735  150.249867
2076   84   37   42    25.496748  81.134491  6.691074  169.928823
2003   86   40   39    25.721009  88.165136  6.207460  175.608670
1744   60   58   51    42.072138  92.922031  6.840802  165.741297
859    23   75   17    24.874255  64.002139  7.198076   48.281375
1272   34  133  202    15.314135  80.097114  5.804799   74.821447
20     89   45   36    21.325042  80.474764  6.442475  185.497473
1647    9   10   10    22.355105  93.522119  6.010392  101.516459
649     1   48   24    29.345946  85.604726  6.232837   59.036300
1161   23   24   32    28.121809  46.168886  5.630620   93.302474
381    11   78   22    23.897568  22.743790  5.940547  112.661643
1278   39  129  203    34.389225  83.183928  5.863997   71.030016
605     9   57   24    29.892328  89.715033  7.165121   42.994990
1665   39   21    9    13.208444  94.027694  6.354023  106.269616
495    35   71   17    29.892866  66.353751  6.931925  198.140300
1010  118   88   52    28.650039  82.687525  5.843163   98.750844
83     67   43   39    26.043720  84.969072  5.999969  186.753677
461    20   77   23    34.872487  38.837860  5.180272  148.250279
994    32   25   35    18.099032  85.707863  5.892914  107.005098
2195  107   34   32    26.774637  66.413269  6.780064  177.774507
1437  120    8   46    29.556575  90.709373  6.732834   28.365356
715    36   66   15    30.085454  69.348120  6.668239   67.136744
1724   31   48   45    40.788818  92.909514  6.563135  132.792359
1738   44   57   53    42.304958  90.514318  6.931721   74.876786
931    34   21   42    18.759277  89.934576  6.648687  111.019674
374    12   61   19    19.331626  24.139950  5.655727   68.512534
270    42   74   83    19.258256  14.280419  7.545258   65.780420
678    27   56   20    29.211422  87.114978  6.418743   51.538482
694     4   40   21    28.797281  80.457444  6.725551   44.300705
1121   36   25   33    27.983928  53.330189  5.548585   99.614657
464    36   80   21    33.647696  48.414901  7.066087  100.467328
1446  106   20   51    29.730197  90.970157  6.342573   20.490356
1157   22   17   26    28.698181  47.718757  4.754435   99.642454
596    22   51   16    27.965837  61.349001  8.639586   70.104721
429     1   76   19    24.185532  46.687468  6.669529  177.337800
1473   94    5   55    28.585465  91.892168  6.085682   26.883726
25     66   53   41    25.075635  80.523891  7.778915  257.003887
907     6   30   40    22.770356  91.454985  6.361374  106.965920
1491   87   21   52    27.350630  94.291195  6.067665   27.212440
458    16   77   22    31.484693  35.639561  6.574210  100.546816
1530   37  126  196    23.599973  90.975977  5.596449  107.172819
680    38   36   21    28.029526  84.884573  6.556373   36.120429
78     77   36   37    26.884449  81.460337  6.136132  194.576656
366    20   69   15    23.442607  22.772559  5.9

# Scale the features using MinMaxScaler

In [25]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()

X_train = ms.fit_transform(X_train)
X_test = ms.transform(X_test)

In [26]:
X_train

array([[0.12142857, 0.07857143, 0.045     , ..., 0.9089898 , 0.48532225,
        0.29685161],
       [0.26428571, 0.52857143, 0.07      , ..., 0.64257946, 0.56594073,
        0.17630752],
       [0.05      , 0.48571429, 0.1       , ..., 0.57005802, 0.58835229,
        0.08931844],
       ...,
       [0.07857143, 0.22142857, 0.13      , ..., 0.43760347, 0.46198144,
        0.28719815],
       [0.07857143, 0.85      , 0.995     , ..., 0.76763665, 0.44420505,
        0.18346657],
       [0.22857143, 0.52142857, 0.085     , ..., 0.56099735, 0.54465022,
        0.11879596]])

# Training Models

In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import ExtraTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

# create instances of all models
models = {
    'Logistic Regression': LogisticRegression(),
    'Naive Bayes': GaussianNB(),
    'Support Vector Machine': SVC(),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Bagging': BaggingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'Extra Trees': ExtraTreeClassifier(),
}


for name, model in models.items():
    model.fit(X_train,y_train)
    ypred = model.predict(X_test)
    
    print(f"{name}  with accuracy : {accuracy_score(y_test,ypred)}")
    print("Confusion matrix : ",confusion_matrix(y_test,ypred))
    print("==========================================================")
    

Logistic Regression  with accuracy : 0.9181818181818182
Confusion matrix :  [[16  0  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 6  0 16  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1]
 [ 0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 27  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  3  0  0  0  0  0]
 [ 0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  

In [28]:
# finally selected randomforest model

rfc = RandomForestClassifier()
rfc.fit(X_train,y_train)
ypred = rfc.predict(X_test)
accuracy_score(y_test,ypred)

0.9931818181818182

In [29]:
# or gausianjb
gnb = GaussianNB()
gnb.fit(X_train,y_train)
ypred = gnb.predict(X_test)
accuracy_score(y_test,ypred)

0.9954545454545455

# Predictive System

In [30]:
def recommendation(N,P,k,temperature,humidity,ph,rainfal):
    features = np.array([[N,P,k,temperature,humidity,ph,rainfal]])
    transformed_features = ms.fit_transform(features)
    prediction = rfc.predict(transformed_features)
    print(prediction)
    return prediction[0] 

In [31]:
# new inputs


N = 40
P = 50
k = 50
temperature = 40.0
humidity = 20
ph = 100
rainfall = 100

predict = recommendation(N,P,k,temperature,humidity,ph,rainfall)

crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
                 8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Grapes", 12: "Mango", 13: "Banana",
                 14: "Pomegranate", 15: "Lentil", 16: "Blackgram", 17: "Mungbean", 18: "Mothbeans",
                 19: "Pigeonpeas", 20: "Kidneybeans", 21: "Chickpea", 22: "Coffee"}

if predict in crop_dict:
    crop = crop_dict[predict]
    print("{} is a best crop to be cultivated ".format(crop))
else:
    print("Sorry are not able to recommend a proper crop for this environment")

[20]
Kidneybeans is a best crop to be cultivated 


In [32]:
# new inputs 2


N = 100
P = 90
k = 100
temperature = 50.0
humidity = 90.0
ph = 100
rainfall = 202.0

predict = recommendation(N,P,k,temperature,humidity,ph,rainfall)

crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
                 8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Grapes", 12: "Mango", 13: "Banana",
                 14: "Pomegranate", 15: "Lentil", 16: "Blackgram", 17: "Mungbean", 18: "Mothbeans",
                 19: "Pigeonpeas", 20: "Kidneybeans", 21: "Chickpea", 22: "Coffee"}

if predict in crop_dict:
    crop = crop_dict[predict]
    print("{} is a best crop to be cultivated ".format(crop))
else:
    print("Sorry are not able to recommend a proper crop for this environment")

[20]
Kidneybeans is a best crop to be cultivated 


In [33]:
# new inputs 2
N = 10
P = 10
k = 10
temperature = 15.0
humidity = 80.0
ph = 4.5
rainfall = 10.0

predict = recommendation(N,P,k,temperature,humidity,ph,rainfall)

crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
                 8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Grapes", 12: "Mango", 13: "Banana",
                 14: "Pomegranate", 15: "Lentil", 16: "Blackgram", 17: "Mungbean", 18: "Mothbeans",
                 19: "Pigeonpeas", 20: "Kidneybeans", 21: "Chickpea", 22: "Coffee"}

if predict in crop_dict:
    crop = crop_dict[predict]
    print("{} is a best crop to be cultivated ".format(crop))
else:
    print("Sorry are not able to recommend a proper crop for this environment")

[20]
Kidneybeans is a best crop to be cultivated 


In [36]:
import pickle
pickle.dump(rfc,open('D:\\AI based crop Project files\\model.pkl','wb'))
pickle.dump(ms,open('D:\\AI based crop Project files\\standscaler (1).pkl','wb'))